---
title: "Assigment - Naive Bayes DIY"
author:
  - Qiwen Chen - Author
  - Thanh Hung Lê - Reviewer
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
   html_notebook:
    toc: true
    toc_depth: 2
---

```{r message=TRUE, warning=TRUE, include=FALSE}
library(tidyverse)
library(tm)
library(caret)
library(wordcloud)
library(e1071)
library(readr)
```

---

## Business Understanding
text and code here

## Data Understanding
text and code here
```{r}
url <- "https://raw.githubusercontent.com/HAN-M3DM-Data-Mining/assignments/master/datasets/NB-reddit-hate-speech.csv"
rawDF <- read_csv(url)
head(rawDF)
```

```{r}
rawDF$type <- rawDF$hate_speech_idx %>% factor %>% relevel("n/a")
class(rawDF$type)

hateful <- rawDF %>% filter(hate_speech_idx != "n/a")
normal <- rawDF %>% filter(hate_speech_idx == "n/a")

wordcloud(hateful$hate_speech_idx, max.words = 20, scale = c(4, 0.8), colors= c("indianred1","indianred2","indianred3","indianred"))
wordcloud(normal$hate_speech_idx, max.words = 20, scale = c(4, 0.8), colors= c("lightsteelblue1","lightsteelblue2","lightsteelblue3","lightsteelblue"))
```


## Data Preparation
text and code here
```{r}
rawCorpus <- Corpus(VectorSource(rawDF$text))
inspect(rawCorpus[1:3])

cleanCorpus <- rawCorpus %>% tm_map(tolower) %>% tm_map(removeNumbers)

cleanCorpus <- cleanCorpus %>% tm_map(tolower) %>% tm_map(removeWords, stopwords()) %>% tm_map(removePunctuation)

cleanCorpus <- cleanCorpus %>% tm_map(stripWhitespace)

tibble(Raw = rawCorpus$content[1:3], Clean = cleanCorpus$content[1:3])
```
```{r}
cleanDTM <- cleanCorpus %>% DocumentTermMatrix
inspect(cleanDTM)
```

```{r}
set.seed(1234)
trainIndex <- createDataPartition(rawDF$type, p = .75, 
                                  list = FALSE, 
                                  times = 1)
head(trainIndex)

# Apply split indices to DF
trainDF <- rawDF[trainIndex, ]
testDF <- rawDF[-trainIndex, ]

# Apply split indices to Corpus
trainCorpus <- cleanCorpus[trainIndex]
testCorpus <- cleanCorpus[-trainIndex]

# Apply split indices to DTM
trainDTM <- cleanDTM[trainIndex, ]
testDTM <- cleanDTM[-trainIndex, ]
```

```{r}
freqWords <- trainDTM %>% findFreqTerms(5)
trainDTM <-  DocumentTermMatrix(trainCorpus, list(dictionary = freqWords))
testDTM <-  DocumentTermMatrix(testCorpus, list(dictionary = freqWords))

convert_counts <- function(x) {
  x <- ifelse(x > 0, 1, 0) %>% factor(levels = c(0,1), labels = c("No", "Yes"))
}

nColsDTM <- dim(trainDTM)[2]
trainDTM <- apply(trainDTM, MARGIN = 2, convert_counts)
testDTM <- apply(testDTM, MARGIN = 2, convert_counts)

head(trainDTM[,1:10])
```


## Modeling
text and code here
```{r}
nbayesModel <-  naiveBayes(trainDTM, trainDF$type, laplace = 1)

predVec <- predict(nbayesModel, testDTM)
confusionMatrix(predVec, testDF$type, positive = "hateful", dnn = c("Prediction", "True"))
```


## Evaluation and Deployment
text and code here
